name: Coduo Backend CD

on:
  push:
    branches: [ "main" ]

permissions: write-all
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: make prod application.yml
      run: |
        rm -rf ./src/main/resources/application.yml
        touch ./src/main/resources/application.yml

        echo ${{secrets.PRODYML}} | base64 --decode > ./src/main/resources/application.yml
      shell: bash

    - name: Gradle Caching
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Grant Execute Permission For Gradlew
      run: chmod +x gradlew

    - name: Build With Gradle
      run: ./gradlew build -x test

    - name: Docker build & Push
      run: |
        docker login -u ${{secrets.DOCKER_ID}} -p ${{secrets.DOCKER_PASSWORD}}
        docker build -t ${{secrets.DOCKER_REPO}}/coduo_springboot_app:latest .
        docker push ${{ secrets.DOCKER_REPO }}/coduo_springboot_app:latest

    - name: Deploy Images with Docker compose
      uses: appleboy/ssh-action@master
      env:
        COMPOSE: "./backend/be-docker-compose.yml"
      with:
        username: ec2-user
        host: ${{secrets.EC2_HOST}}
        key: ${{secrets.EC2_PRIVATE_KEY}}
        envs: COMPOSE
        script_stop: true
        script: |
          docker compose -f $COMPOSE down
          docker pull ${{secrets.DOCKER_REPO}}/coduo_springboot_app:latest
          docker compose -f $COMPOSE up -d
