name: Coduo Backend CI

on:
  pull_request:
    branches: [ "main" ]

permissions: write-all
jobs:
  build-and-test:
    runs-on: coduo-backend-ec2
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Set up Test MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        host port: 33600
        container port: 3306
        mysql database: 'testdb'
        mysql root password: testPw1234!
        
    - name: Make test application.yml
      run: |
        rm -rf ./src/main/resources/application.yml
        touch ./src/main/resources/application.yml
        echo ${{ secrets.TESTYML }} | base64 --decode > ./src/main/resources/application.yml
      shell: bash

    - name: Gradle Caching
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Grant Execute Permission For Gradlew
      run: chmod +x gradlew

    - name: Build With Gradle
      run: ./gradlew build -x test

    - name: Running Test Code
      run: ./gradlew --info test

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: ${{ always() }}
      with:
        files: build/test-results/**/*.xml

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: success() || failure() # always run even if the previous step fails
      with:
        report_paths: '**/build/test-results/test/TEST-*.xml'
